#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# vim stuff
ln -fs ${BASEDIR}/vimrc ~/.vimrc
ln -fs ${BASEDIR}/vim/ ~/.vim

# tmux
ln -fs ${BASEDIR}/tmux.conf ~/.tmux.conf

# git
ln -fs ${BASEDIR}/gitconfig ~/.gitconfig
