#!/bin/bash
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# vim stuff
ln -fs ${BASEDIR}/vimrc ~/.vimrc
ln -fs ${BASEDIR}/vim/ ~/.vim

# tmux
ln -fs ${BASEDIR}/tmux.conf ~/.tmux.conf

# git
ln -fs ${BASEDIR}/gitconfig ~/.gitconfig

# i3
ln -fs ${BASEDIR}/i3_config ~/.i3/config

# polybar
ln -fs ${BASEDIR}/polybar ~/.config/polybar/config

vim +PluginInstall qall
